// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	context "context"

	classservice "github.com/angusgmorrison/hexagonal/internal/service/classservice"

	mock "github.com/stretchr/testify/mock"

	primitive "github.com/angusgmorrison/hexagonal/internal/primitive"

	testing "testing"
)

// AtomicClassScribe is an autogenerated mock type for the AtomicClassScribe type
type AtomicClassScribe struct {
	mock.Mock
}

// Begin provides a mock function with given fields: ctx
func (_m *AtomicClassScribe) Begin(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Commit provides a mock function with given fields:
func (_m *AtomicClassScribe) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnrollStudents provides a mock function with given fields: ctx, c, s
func (_m *AtomicClassScribe) EnrollStudents(ctx context.Context, c classservice.Course, s classservice.Students) (classservice.Class, error) {
	ret := _m.Called(ctx, c, s)

	var r0 classservice.Class
	if rf, ok := ret.Get(0).(func(context.Context, classservice.Course, classservice.Students) classservice.Class); ok {
		r0 = rf(ctx, c, s)
	} else {
		r0 = ret.Get(0).(classservice.Class)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, classservice.Course, classservice.Students) error); ok {
		r1 = rf(ctx, c, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClassByCourseCode provides a mock function with given fields: ctx, courseCode
func (_m *AtomicClassScribe) GetClassByCourseCode(ctx context.Context, courseCode string) (classservice.Class, error) {
	ret := _m.Called(ctx, courseCode)

	var r0 classservice.Class
	if rf, ok := ret.Get(0).(func(context.Context, string) classservice.Class); ok {
		r0 = rf(ctx, courseCode)
	} else {
		r0 = ret.Get(0).(classservice.Class)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, courseCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentsByEmail provides a mock function with given fields: ctx, emails
func (_m *AtomicClassScribe) GetStudentsByEmail(ctx context.Context, emails []primitive.EmailAddress) (classservice.Students, error) {
	ret := _m.Called(ctx, emails)

	var r0 classservice.Students
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.EmailAddress) classservice.Students); ok {
		r0 = rf(ctx, emails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(classservice.Students)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []primitive.EmailAddress) error); ok {
		r1 = rf(ctx, emails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields:
func (_m *AtomicClassScribe) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAtomicClassScribe creates a new instance of AtomicClassScribe. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAtomicClassScribe(t testing.TB) *AtomicClassScribe {
	mock := &AtomicClassScribe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
