// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// logger is an autogenerated mock type for the logger type
type logger struct {
	mock.Mock
}

// Printf provides a mock function with given fields: format, args
func (_m *logger) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// newLogger creates a new instance of logger. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newLogger(t testing.TB) *logger {
	mock := &logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
