// Code generated by mockery v2.12.0. DO NOT EDIT.

package classservice

import (
	context "context"
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// Enroll provides a mock function with given fields: ctx, er
func (_m *MockInterface) Enroll(ctx context.Context, er EnrollmentRequest) error {
	ret := _m.Called(ctx, er)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, EnrollmentRequest) error); ok {
		r0 = rf(ctx, er)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockInterface creates a new instance of MockInterface. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterface(t testing.TB) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
