// Code generated by mockery v2.12.0. DO NOT EDIT.

package classservice

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// mockLogger is an autogenerated mock type for the logger type
type mockLogger struct {
	mock.Mock
}

// Printf provides a mock function with given fields: format, args
func (_m *mockLogger) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// newMockLogger creates a new instance of mockLogger. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLogger(t testing.TB) *mockLogger {
	mock := &mockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
